# Generated by Django 5.2.7 on 2026-06-10 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_remove_appointment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['room', 'number']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['service', 'number']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='provision',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinical.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provision',
            name='min_quantity_alert',
            field=models.IntegerField(default=10, help_text="Seuil d'alerte de stock faible"),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location_lat',
            field=models.FloatField(blank=True, help_text='Latitude GPS pour navigation', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location_long',
            field=models.FloatField(blank=True, help_text='Longitude GPS pour navigation', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supporttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporttask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supporttask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supporttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='clinical.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_open_h24',
            field=models.BooleanField(default=False, help_text='Ouvert 24h/24 (urgences, labo, etc.)'),
        ),
        migrations.AlterField(
            model_name='supporttask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supporttask',
            name='location_lat',
            field=models.FloatField(blank=True, help_text='Latitude pour la localisation', null=True),
        ),
        migrations.AlterField(
            model_name='supporttask',
            name='location_long',
            field=models.FloatField(blank=True, help_text='Longitude pour la localisation', null=True),
        ),
        migrations.AlterField(
            model_name='supporttask',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tasks', to='clinical.service'),
        ),
        migrations.AlterField(
            model_name='supporttask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='supporttask',
            name='task_type',
            field=models.CharField(choices=[('CLEANING', 'Propreté'), ('SECURITY', 'Sécurité'), ('MAINTENANCE', 'Maintenance')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='provision',
            unique_together={('name', 'service')},
        ),
    ]
