# Generated by Django 5.2.7 on 2026-07-01 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_alter_bed_options_alter_room_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='clinical_ap_appoint_f7fb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='clinical_ap_status_abd575_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='clinical_ap_doctor__a31df2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='clinical_se_name_10f83d_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='clinical_se_code_8dd1bd_idx'),
        ),
    ]
