# Generated by Django 5.2.16 on 2026-07-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_payment_methods_invoice_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('date_terme', models.DateField()),
                ('next_visit', models.DateField()),
                ('status', models.CharField(default='Suivi en cours', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_visit'],
            },
        ),
        migrations.CreateModel(
            name='PediatricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taille', models.PositiveIntegerField(blank=True, help_text='cm', null=True)),
                ('groupe_sanguin', models.CharField(blank=True, default='', max_length=5)),
                ('vaccin_date', models.DateField()),
                ('status', models.CharField(default='Suivi actif', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
