# Generated by Django 6.0.7 on 2026-07-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_pediatric_maternity_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedclinicalrecord',
            options={'ordering': ['-archived_at']},
        ),
        migrations.AlterModelOptions(
            name='deathrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='archivedclinicalrecord',
            name='cause_of_death',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='archivedclinicalrecord',
            name='original_matricule',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='archivedclinicalrecord',
            name='original_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='archivedclinicalrecord',
            name='patient_full_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='archivedclinicalrecord',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='complications',
            field=models.TextField(blank=True, help_text='Complications ou détails supplémentaires', null=True),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='is_dossier_purged',
            field=models.BooleanField(default=False, help_text='True après purge automatique (7 jours)'),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service où le décès a eu lieu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records', to='clinical.service'),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, help_text="Date d'expiration MM/AA", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='4 derniers chiffres de la carte bancaire', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='archivedclinicalrecord',
            name='snapshot',
            field=models.JSONField(default=dict, help_text="Copie des données de soins au moment de l'archivage"),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='cause',
            field=models.TextField(blank=True, help_text='Cause principale du décès', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Paiement sur place (espèces)'), ('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('CARD', 'Carte bancaire')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='deathrecord',
            index=models.Index(fields=['service'], name='clinical_de_service_22172e_idx'),
        ),
        migrations.AddIndex(
            model_name='deathrecord',
            index=models.Index(fields=['cause'], name='clinical_de_cause_3df4d5_idx'),
        ),
    ]
