# Generated by Django 5.2.7 on 2026-06-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_mfacode_id_alter_user_id'),
        ('clinical', '0006_alter_bed_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clinical.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('SECRETARY_GENERAL', 'Secrétaire Générale'), ('SECRETARY_SERVICE', 'Secrétaire de Service'), ('DOCTOR', 'Médecin'), ('BIOLOGIST', 'Biologiste'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
