# Generated by Django 6.0.7 on 2026-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_logistics', '0003_alter_invoice_id_alter_invoiceitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('SCHOOL', 'Ecole'), ('INSURANCE', 'Assurance')], default='SCHOOL', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contract_reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
